### ISSUE TITLE
2.3.0 use of unstable library feature 'io_safety'

### ISSUE THREAD

**Issue by Antiarchitect** [smol-rs/polling#41]
After update to 2.3.0 having these errors:

```
error[E0658]: use of unstable library feature 'io_safety'
  --> /home/andrey/.cargo/registry/src/github.com-1ecc6299db9ec823/polling-2.3.0/src/epoll.rs:10:25
   |
10 | use std::os::unix::io::{AsFd, BorrowedFd};
   |                         ^^^^
   |
   = note: see issue #87074 <https://github.com/rust-lang/rust/issues/87074> for more information
   = help: add `#![feature(io_safety)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'io_safety'
  --> /home/andrey/.cargo/registry/src/github.com-1ecc6299db9ec823/polling-2.3.0/src/epoll.rs:10:31
   |
10 | use std::os::unix::io::{AsFd, BorrowedFd};
   |                               ^^^^^^^^^^
   |
   = note: see issue #87074 <https://github.com/rust-lang/rust/issues/87074> for more information
   = help: add `#![feature(io_safety)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'io_safety'
   --> /home/andrey/.cargo/registry/src/github.com-1ecc6299db9ec823/polling-2.3.0/src/epoll.rs:239:5
    |
239 | /     fn as_fd(&self) -> BorrowedFd<'_> {
240 | |         // SAFETY: lifetime is bound by "self"
241 | |         unsafe { BorrowedFd::borrow_raw(self.as_raw_fd()) }
242 | |     }
    | |_____^
    |
    = note: see issue #87074 <https://github.com/rust-lang/rust/issues/87074> for more information
    = help: add `#![feature(io_safety)]` to the crate attributes to enable
```

```
rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)

cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)
```

Is it me doing something wrong or is it a real bug? I'm not using `polling` directly but it is in dependencies of other packages I use, e.g. async-io, ntex etc.

**Comment by taiki-e** [comment]
Could you try with toolchain override shorthand (`cargo +stable build`)?
If old cargo/rustc is installed via the package manager, they may take precedence partially (like https://github.com/tokio-rs/tokio/issues/3355#issuecomment-751482243 or https://github.com/tokio-rs/bytes/issues/323#issuecomment-773312406).

**Comment by Antiarchitect** [comment]
Sorry guys. It's cargo udeps is complaining as it runs with `+nightly`. Closing.
